server:
  port: 8081


spring:
  application:
    name: kafka-demo
  cassandra:
    contact-points: localhost     # Cassandra node address
    port: 9042                    # Cassandra native transport port
    keyspace-name: easy_taxi   # Keyspace name
    local-datacenter: datacenter1 # Datacenter name
    schema-action: none           # Schema management action (e.g., 'create', 'create-if-not-exists', 'none')
    connection:
      init-query-timeout: 5000ms  # Initial connection timeout
    request:
      timeout: 5000ms             # Timeout for CQL queries\

  kafka:
    bootstrap-servers: ${bootstrap_servers:localhost:9092}
    consumer:
      group-id: ${group_id:kafka-demo}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1

kafka:
  topic:
    rides-detail-events: ${topic_name:rides-events}


