server:
  port: 9090
spring:
  application:
    name: kafka-producer-wikimedia

kafka:
  bootstrap-servers: ${kafka_bootstrap_servers:127.0.0.1:9092}
  topic:
    wikimedia-recent-change: ${wikimedia_recent_change_topic_name:wikimedia-recent-change}

wikimedia:
  base-uri: https://stream.wikimedia.org
  change-stream-uri: /v2/stream/recentchange
