spring:
  application:
    name: kafka-consumer-opensearch

  kafka:
    streams:
      application-id: my-kafka-streams-app
      bootstrap-servers: localhost:9092
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde


kafka:
  bootstrap-servers: ${kafka_bootstrap_servers:127.0.0.1:9092}
  topic:
    wikimedia-recent-change: ${wikimedia_recent_change_topic_name:wikimedia-recent-change}
  group-id:
    default: ${group_id:ali-ahmad}
  auto-offset-reset:
    default: ${auto_offset_reset:earliest}



opensearch:
  host: localhost
  port: 9200
  protocol: https
  username: admin
  password: S6^8JH&Sb5Q0@dx
  connection-timeout: 5000
  socket-timeout: 60000
  ssl:
    verification-mode: none
