spring:
  application:
    name: kafka-consumer-opensearch


kafka:
  bootstrap-servers: ${kafka_bootstrap_servers:127.0.0.1:9092}
  topic:
    wikimedia-recent-change: ${wikimedia_recent_change_topic_name:wikimedia-recent-change}
  group-id:
    default: ${group_id:ali-ahmad}
  auto-offset-reset:
    default: ${auto_offset_reset:latest}
