graph TB
    subgraph Topic-A
        P0[Topic-A Partition 0]
        P1[Topic-A Partition 1]
        P2[Topic-A Partition 2]
    end

    subgraph Topic-B
        Q0[Topic-B Partition 0]
        Q1[Topic-B Partition 1]
    end

    subgraph Broker-1
        B1P0[A-P0 Leader]
        B1P1[A-P1 Follower]
        B1P2[A-P2 Follower]
        B1Q0[B-P0 Leader]
        B1Q1[B-P1 Follower]
    end

    subgraph Broker-2
        B2P0[A-P0 Follower]
        B2P1[A-P1 Leader]
        B2P2[A-P2 Follower]
        B2Q0[B-P0 Follower]
        B2Q1[B-P1 Leader]
    end

    subgraph Broker-3
        B3P0[A-P0 Follower]
        B3P1[A-P1 Follower]
        B3P2[A-P2 Leader]
        B3Q0[B-P0 Follower]
        B3Q1[B-P1 Follower]
    end

    P0 --> B1P0
    P0 --> B2P0
    P0 --> B3P0

    P1 --> B2P1
    P1 --> B1P1
    P1 --> B3P1

    P2 --> B3P2
    P2 --> B1P2
    P2 --> B2P2

    Q0 --> B1Q0
    Q0 --> B2Q0
    Q0 --> B3Q0

    Q1 --> B2Q1
    Q1 --> B1Q1
    Q1 --> B3Q1

    classDef leader fill:#f96,stroke:#333,stroke-width:2px
    classDef follower fill:#99ca,stroke:#333
    class B1P0,B2P1,B3P2,B1Q0,B2Q1 leader
    class B1P1,B1P2,B2P0,B2P2,B3P0,B3P1,B2Q0,B3Q0,B1Q1,B3Q1 follower
